name: Publish to GitHub Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish -c Release -o bin
    - name: Publish
      run: |
        cd bin
        git init
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:hippibruder/nonogramwasm.git main:gh-pages
